export const filterOption = [{
    type: 'Between',
    value: ['', ''],
    field: 'incomeDate',
    component: 'date',
    name: '日期'
}, {
    type: 'In',
    value: [],
    field: 'addressId',
    model: 'address',
    component: 'select',
    name: '地点'
}, {
    type: 'In',
    value: [],
    field: 'incomeCategoryId',
    model: 'incomeCategory',
    component: 'select',
    name: '类别'
}, {
    type: 'In',
    value: [],
    field: 'accountId',
    model: 'account',
    component: 'select',
    name: '账户',
}, {
    type: 'In',
    value: [],
    field: 'incomeStoreId',
    model: 'incomeStore',
    component: 'select',
    name: '来源'
}, {
    type: 'Like',
    value: '',
    field: 'content',
    component: 'input',
    name: '收入'
}, {
    type: 'Between',
    value: ['', ''],
    field: 'amount',
    component: 'range',
    name: '金额'
}, {
    type: 'In',
    value: [],
    field: 'peopleId',
    model: 'people',
    component: 'select',
    name: '参与人'
}, {
    type: 'In',
    value: [],
    field: 'lableId',
    model: 'label',
    component: 'select',
    name: '标签'
}, {
    type: 'Like',
    value: '',
    field: 'memo',
    component: 'input',
    name: '备注'
}];
