export const filterOption = [{
    type: 'Between',
    value: ['', ''],
    field: 'incomeDate',
    component: 'date',
    name: 'IncomeDate'
}, {
    type: 'In',
    value: [],
    field: 'addressId',
    model: 'address',
    component: 'select',
    name: 'Address'
}, {
    type: 'In',
    value: [],
    field: 'incomeCategoryId',
    model: 'incomeCategory',
    component: 'select',
    name: 'IncomeCategory'
}, {
    type: 'In',
    value: [],
    field: 'accountId',
    model: 'account',
    component: 'select',
    name: 'Account',
}, {
    type: 'In',
    value: [],
    field: 'incomeStoreId',
    model: 'incomeStore',
    component: 'select',
    name: 'IncomeStore'
}, {
    type: 'Like',
    value: '',
    field: 'content',
    component: 'input',
    name: 'Content'
}, {
    type: 'Between',
    value: ['', ''],
    field: 'amount',
    component: 'range',
    name: 'Amount'
}, {
    type: 'In',
    value: [],
    field: 'peopleId',
    model: 'people',
    component: 'label-people',
    name: 'People'
}, {
    type: 'In',
    value: [],
    field: 'lableId',
    model: 'label',
    component: 'label-people',
    name: 'Label'
}, {
    type: 'Like',
    value: '',
    field: 'memo',
    component: 'input',
    name: 'Memo'
}];
